name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        working-directory: ./frontend

      - name: Copy index.html to 404.html
        run: cp ./frontend/dist/index.html ./frontend/dist/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAGES_PAT }}
          publish_dir: ./frontend/dist